### ISSUE TITLE
Update playbook lr-pocketsnes changed to lr-snes9x2002

### ISSUE THREAD

**Issue by Nolaan** [adrianmoisey/ansible-retropie#1]
failed: [10.42.0.217] (item=lr-pocketsnes) => {"changed": true, "cmd": "./retropie_packages.sh lr-pocketsnes depends; ./retropie_packages.sh lr-pocketsnes install_bin; ./retropie_packages.sh lr-pocketsnes configure", "delta": "0:00:14.241155", "end": "2017-06-03 13:17:00.744244", "failed": true, "item": "lr-pocketsnes", "rc": 2, "start": "2017-06-03 13:16:46.503089", "stderr": "", "stderr_lines": [], "stdout": "No module 'lr-pocketsnes' found for platform rpi3\nNo module 'lr-pocketsnes' found for platform rpi3\nNo module 'lr-pocketsnes' found for platform rpi3", "stdout_lines": ["No module 'lr-pocketsnes' found for platform rpi3", "No module 'lr-pocketsnes' found for platform rpi3", "No module 'lr-pocketsnes' found for platform rpi3"]}

**Comment by adrianmoisey** [comment]
I've fixed in https://github.com/adrianmoisey/ansible-retropie/commit/504b88ccede8d7a24fbf4ff1e61f39af70c56049

Let me know if there are other issues.

**Comment by Nolaan** [comment]
Actually, I'm also trying to launch it via VNC but it doesn't work. I'll try to investigate and submit an issue. Thanks for the repo and the update!

**Comment by adrianmoisey** [comment]
Awesome.
The ansible scripts are sort of catered to my personal use, but I'd love to make them more generic and allow more people use them, but I don't have much time to do that.
So if you have any issues or improvements, please do let me know, I'll see what I can do.
